name: Python Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # Install test dependencies; include email validation extra required by pydantic EmailStr
          pip install fastapi uvicorn pydantic[email] httpx pytest

      - name: Run pytest
        run: pytest -q
