name: Example Apps Smoke

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Smoke - Next build
        run: npm run ci:smoke:web-next

      - name: Smoke - Remix build
        run: npm run ci:smoke:web-remix

      - name: Smoke - Expo lint
        run: npm run ci:smoke:web-expo
