name: Example Apps Smoke

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  smoke:
    runs-on: ubuntu-latest
    # Removed NODE_ENV=production - it was causing npm ci to skip devDependencies
    # which includes nx and all @nx/* packages needed for builds
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Sync Python dependencies
        run: uv sync

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Smoke - Next build
        run: npm run ci:smoke:web-next

      - name: Smoke - Remix build
        run: npm run ci:smoke:web-remix

      - name: Smoke - Expo lint
        run: npm run ci:smoke:web-expo
