name: Type Sync

on:
  # Run on pushes to main branch
  push:
    branches:
      - main
  # Run on pull requests to main branch
  pull_request:
    branches:
      - main
  # Run on schedule (daily at 2 AM UTC)
  schedule:
    - cron: '0 2 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  type-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Cache disabled to force fresh install
          # cache: 'npm'

      - name: Use Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Node.js dependencies
        run: npm ci --legacy-peer-deps

      - name: Install type generator dependencies
        run: npm ci --legacy-peer-deps
        working-directory: tools/type-generator

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any Python dependencies needed for type generation here
          # pip install -r requirements.txt

      - name: Build type generator
        run: npm run build
        working-directory: tools/type-generator

      - name: Generate TypeScript and Python types
        run: |
          # Generate TypeScript types
          node tools/type-generator/cli.js generate tests/fixtures/database-schema.json -o libs/shared/database-types

          # Generate Python types
          python libs/shared/type_system/generators/db_to_python.py tests/fixtures/database-schema.json libs/backend/type_utils

      - name: Verify type parity
        run: |
          # Verify structural parity between TypeScript and Python types
          node tools/type-generator/cli.js verify libs/shared/database-types libs/backend/type_utils

      - name: Check for changes
        id: git-check
        run: |
          git add .
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: sync types from database schema'
          title: 'Type Sync: Update generated types'
          body: |
            This PR was automatically generated by the Type Sync workflow.

            Changes were detected in the generated TypeScript and Python types.
            Please review and merge if appropriate.
          branch: type-sync/automated-changes
          delete-branch: true
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
